fix import terraform linux web app

diff --git a/.github/workflows/iac.yml b/.github/workflows/iac.yml
--- a/.github/workflows/iac.yml
+++ b/.github/workflows/iac.yml
@@ -44,9 +44,9 @@ jobs:
         run: cat .terraform.lock.hcl
 
       - name: Terraform import existing Linux Web App
+        working-directory: ./iac
         run: |
-          terraform init
-          terraform import azurerm_linux_web_app.app /subscriptions/TWOJE_SUBSCRIPTION_ID/resourceGroups/rg-github-iac/providers/Microsoft.Web/sites/github-iac-webapp || echo "Import failed or already imported"
+          terraform import azurerm_linux_web_app.app /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-github-iac/providers/Microsoft.Web/sites/github-iac-webapp || echo "Import failed or already imported"
 
       - name: Terraform Validate
         working-directory: ./iac
